"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = '[➜](bold green)'

[git_commit]
commit_hash_length = 6
tag_disabled = false

[c]
format = 'via [$name $version]($style)'

[directory]
truncation_length = 8
truncation_symbol = '…/'
