"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 3000

[character]
success_symbol = '[➜](bold green)'

[git_commit]
commit_hash_length = 7
tag_disabled = false

[c]
format = "via [$name $version]($style) "

[directory]
truncation_length = 8
truncation_symbol = '…/'

[git_branch]
truncation_length = 20

[memory_usage]
format = "using [$ram_pct RAM]($style) "
disabled = false

[package]
disabled = true

[status]
format = "[$common_meaning $status]($style) "
disabled = false
